### ISSUE TITLE
Wrong intersection, e.g., '1.0.0 - 1.5.3'

### ISSUE THREAD

**Issue by mearns** [snyamathi/semver-intersect#12]
When I try the following intersections, I get the wrong results:

```javascript
intersect('1.0.0 - 1.5.3') // gives ~1.0.0
intersect('>=1.0.0', '<=1.5.3') // gives ~1.0.0
```

The input ranges allow for, e.g., 1.4.0, but the returned intersection does not.

**Comment by snyamathi** [comment]
https://github.com/snyamathi/semver-intersect/pull/13
